version: '3.8'

services:
  frontend:
    build:
      context: ./FridgeHub
    ports:
      - "19006:19006"  # Expo's default port for web interface
      - "19000:19000"  # Expo's default port for development tools
      - "19001:19001"  # Expo's default port for iOS
      - "19002:19002"  # Expo's default port for Android
    volumes:
      - ./FridgeHub:/usr/src/app
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
    ports:
      - "9000:9000"
    volumes:
      - ./back-end:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=8000
      - API_VERSION=api/v1
      - MONGO_URL=mongodb+srv://Frenchua:Kt9pJfCHe6fPvw2S@fridgehub.rudbzax.mongodb.net/
      - JWT_SECRET=secret123
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
